inherit_from:
  - enabled.yml
  - disabled.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    # TODO
    # - 'bin/*'
    # - 'db/schema.rb'
    # - 'tmp/**/*'
  DisplayCopNames: true

Style/IndentationConsistency:
  EnforcedStyle: rails

Metrics/LineLength:
  Max: 200
